<template>
<div class="n">
    <div class="te">
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img class="ggg" src="http://www.vgmaps.com/Atlas/GB-GBC/Pokemon-Red,Green(J)&amp;BlueVersions-Kanto.png" usemap="#image-map" />
        <map name="image-map">
            <area target="_parent" @click="seacottage()" alt="Sea Cottage" title="Sea Cottage" coords="4453,451,5031,1" shape="rect" />>
            <area target="_parent" @click="route25()" alt="Route 25" title="Route 25" coords="4366,217,4514,355" shape="rect" />
            <area target="_parent" @click="route24()" alt="Route 24" title="Route 24" coords="3997,331,4145,498" shape="rect" />
            <area target="_parent" @click="cerleanCity()" alt="Cerulean City" title="Cerulean City" coords="3968,539,4224,1056" shape="rect" />
            <area target="_parent" @click="route9()" alt="Route 9" title="Route 9" coords="4509,617,4696,716" shape="rect" />
            <area target="_parent" @click="rockTunnel()" alt="Rock Tunnel" title="Rock Tunnel" coords="5474,930,5567,1028" shape="rect" />
            <area target="_parent" @click="route10()" alt="Route 10" title="Route 10" coords="5478,1052,5567,1175" shape="rect" />
            <area target="_parent" @click="powerPlant()" alt="Power Plant" title="Power Plant" coords="5168,1202,5567,1487" shape="rect" />
            <area target="_parent" @click="lavenderTown()" alt="Lavender Town" title="Lavender Town" coords="5103,1768,5567,2126" shape="rect" />
            <area target="_parent" @click="route11()" alt="Route 12" title="Route 12" coords="5464,2986,5567,3217" shape="rect" />
            <area target="_parent" @click="route8()" alt="Route 8" title="Route 8" coords="4603,1799,4799,1917" shape="rect" />
            <area target="_parent" @click="route5()" alt="Route 5" title="Route 5" coords="4229,1454,4052,1193" shape="rect" />
            <area target="_parent" @click="route11()" alt="Route 11" title="Route 11" coords="4598,2878,4785,2997" shape="rect" />
            <area target="_parent" @click="cave()" alt="Diglett's Cave" title="Diglett's Cave" coords="4224,2879,4366,2983" shape="rect" />
            <area target="_parent" @click="route13()" alt="Route 13" title="Route 13" coords="4686,3807,4913,3930" shape="rect" />
            <area target="_parent" @click="route14()" alt="Route 14" title="Route 14" coords="4106,4179,4317,4351" shape="rect" />
            <area target="_parent" @click="route15()" alt="Route 15" title="Route 15" coords="3294,4403,4165,4556" shape="rect" />
            <area target="_parent" @click="route18()" alt="Route 18" title="Route 18" coords="2187,4339,2649,4571" shape="rect" />
            <area target="_parent" @click="fuchia()" alt="Fuchsia City" title="Fuchsia City" coords="2625,4290,3269,4902" shape="rect" />
            <area target="_parent" @click="seafoam()" alt="SeaFoam Island" title="SeaFoam Island" coords="1852,5410,2236,5809" shape="rect" />
            <area target="_parent" @click="route20()" alt="Sea Route 20" title="Sea Route 20" coords="1281,5390,1773,5798" shape="rect" />
            <area target="_parent" @click="route21()" alt="Sea Route 21" title="Sea Route 21" coords="1385,5320,809,4335" shape="rect" />
            <area target="_parent" @click="pallettown()" alt="Pallet Town" title="Pallet Town" coords="794,3720,1321,4168" shape="rect" />
            <area target="_parent" @click="route1()" alt="Route 1" title="Route 1" coords="1163,3701,1227,3108" shape="rect" />
            <area target="_parent" @click="viridian()" alt="Viridian City" title="Viridian City" coords="765,2587,1385,3168" shape="rect" />
            <area target="_parent" @click="cave()" alt="Diglett's Cave" title="Diglett's Cave" coords="1007,1440,1348,1747" shape="rect" />
            <area target="_parent" @click="pewter()" alt="Pewter City" title="Pewter City" coords="696,827,1355,1403" shape="rect" />
            <area target="_parent" @click="celadon()" alt="Celadon City" title="Celadon City" coords="2462,1678,3259,2328" shape="rect" />
            <area target="_parent" @click="saffron()" alt="Saffron City" title="Saffron City" coords="3589,1723,4229,2294" shape="rect" />
            <area target="_parent" @click="vermillian()" alt="Vermillion City" title="Vermillion City" coords="3501,2868,4200,3429" shape="rect" />
            <area target="_parent" @click="route4()" alt="Route 4" title="Route 4" coords="3604,718,2836,629" shape="rect" />
            <area target="_parent" @click="moon()" alt="Mt Moon" title="Mt Moon" coords="2787,812,2206,596" shape="rect" />
            <area target="_parent" @click="known()" alt="Known Dungeon" title="Known Dungeon" coords="3569,472,3815,585" shape="rect" />
            <area target="_parent" @click="route3()" alt="Route 3" title="Route 3" coords="2128,1033,1463,969" shape="rect" />
            <area target="_parent" @click="route4()" alt="Route 4" title="Route 4" coords="2113,705,2187,946" shape="rect" />
            <area target="_parent" @click="route19()" alt="Route 19" title="Route 19" coords="2792,5481,2689,5028" shape="rect" />
            <area target="_parent" @click="route16()" alt="Route 16" title="Route 16" coords="1906,1740,2349,1863" shape="rect" />
            <area target="_parent" @click="route17()" alt="Route 17" title="Route 17" coords="2270,3142,2123,3918" shape="rect" />
            <area target="_parent" @click="rock()" alt="Rock Tunnel" title="Rock Tunnel" coords="5243,1509,5553,1701" shape="rect" />
            <area target="_parent" @click="indiago()" alt="Indigo Plateau" title="Indigo Plateau" coords="460,468,15,179" shape="rect" />
            <area target="_parent" @click="route23()" alt="Route 23" title="Route 23" coords="420,628,504,978" shape="rect" />
            <area target="_parent" @click="earth()" alt="Earth Badge" title="Earth Badge" coords="583,1207,2,1006" shape="rect" />
            <area target="_parent" @click="volcano()" alt="Volcano Badge" title="Volcano Badge" coords="22,1261,597,1542" shape="rect" />
            <area target="_parent" @click="mash()" alt="Mash Badge" title="Mash Badge" coords="7,1683,627,1939" shape="rect" />
            <area target="_parent" @click="soul()" alt="Soul Badge" title="Soul Badge" coords="1,1975,573,2103" shape="rect" />
            <area target="_parent" @click="rainbow()" alt="Rainbow Badge" title="Rainbow Badge" coords="2,2134,573,2326" shape="rect" />
            <area target="_parent" @click="thunder()" alt="Thunder Badge" title="Thunder Badge" coords="7,2367,563,2584" shape="rect" />
            <area target="_parent" @click="cascade()" alt="Cascade Badge" title="Cascade Badge" coords="2,2615,583,2738" shape="rect" />
            <area target="" @click="route2()" alt="Route 2" title="Route 2" coords="765,1861,878,2417" shape="rect" />
        </map>
    </div>
    <w-app>
        <w-drawer width="60em" v-model="openDrawer" :[position]="true">
            <w-button bg-color="white" @click="openDrawer = false" sm outline round absolute icon="wi-cross">
            </w-button>
            <w-flex column>
                <w-tag xl height="3em" bg-color="primary">{{ name.name1 }}</w-tag>
                <img class="imagestyle" :src="name.imagelink" />
                <w-tag xl class="desc" height="10em" bg-color="primary">{{
            name.description
          }}</w-tag>
          <w-tag xl class="desc1" height="2em" bg-color="primary">No of Checkins Previosuly - {{name.checkin}} </w-tag>
                <a class="link" :href="name.weblink">Click here to go the Website</a>
            </w-flex>
        </w-drawer>
    </w-app>
</div>
</template>

<script>
import landmarks from "../Database/landmarks.json";
import routes from "../Database/KantoRoutesDesc.json";
import cities from "../Database/KantoCityDescription.json";
import badges from "../Database/JsonKantoBadgeDesc.json";
import csv from "../Database/checkin.json"
export default {
    name: "Map",
    data: () => ({
        openDrawer: false,
        name: {
            name1: "",
            description: "",
            imagelink: "",
            weblink: "",
            checkin:""
        },
    }),
    
    methods: {
        calculateCount(placename) {
            let count = 0
            console.log(csv)
            for (let data of csv) {
                if (data.PlaceName == placename) {
                    count = count + 1
                }
                console.log("count", count)
            }
            return count

        },
        indiago() {
            console.log(landmarks[0]);
            this.openDrawer = true;
            this.name.name1 = landmarks[0].landmarkName;
            this.name.description = landmarks[0].landmarkDescription;
            this.name.imagelink = landmarks[0].imageLink;
            this.name.checkin = this.calculateCount("Indigo Plateau")
        },
        viridianf() {
            console.log(landmarks[1]);
            this.openDrawer = true;
            this.name.name1 = landmarks[1].landmarkName;
            this.name.description = landmarks[1].landmarkDescription;
            this.name.imagelink = landmarks[1].imageLink;
            this.name.checkin = this.calculateCount("Viridian Forest")
        },

        moon() {
            console.log(landmarks[2]);
            this.openDrawer = true;
            this.name.name1 = landmarks[2].landmarkName;
            this.name.description = landmarks[2].landmarkDescription;
            this.name.imagelink = landmarks[2].imageLink;
            this.name.checkin = this.calculateCount("Mt. Moon")
        },

        seacottage() {
            console.log(landmarks[3]);
            this.openDrawer = true;
            this.name.name1 = landmarks[3].landmarkName;
            this.name.description = landmarks[3].landmarkDescription;
            this.name.imagelink = landmarks[3].imageLink;
            this.name.checkin = this.calculateCount("Sea Cottage")
        },
        rock() {
            this.openDrawer = true;
            this.name.name1 = landmarks[4].landmarkName;
            this.name.description = landmarks[4].landmarkDescription;
            this.name.imagelink = landmarks[4].imageLink;
            this.name.checkin = this.calculateCount("Rock Tunnel")
        },

        powerPlant() {
            this.openDrawer = true;
            this.name.name1 = landmarks[5].landmarkName;
            this.name.description = landmarks[5].landmarkDescription;
            this.name.imagelink = landmarks[5].imageLink;
            this.name.checkin = this.calculateCount("Power Plant")
        },
        cave() {
            this.openDrawer = true;
            this.name.name1 = landmarks[6].landmarkName;
            this.name.description = landmarks[6].landmarkDescription;
            this.name.imagelink = landmarks[6].imageLink;
            this.name.checkin = this.calculateCount("Diglett's Cave")
        },
        known() {
            this.openDrawer = true;
            this.name.name1 = landmarks[7].landmarkName;
            this.name.description = landmarks[7].landmarkDescription;
            this.name.imagelink = landmarks[7].imageLink;
            this.name.checkin = this.calculateCount("Unknown Dungeon")
        },

        annie() {
            this.openDrawer = true;
            this.name.name1 = landmarks[8].landmarkName;
            this.name.description = landmarks[8].landmarkDescription;
            this.name.imagelink = landmarks[8].imageLink;
            this.name.checkin = this.calculateCount("S.S.Anne")
        },

        seafoam() {
            this.openDrawer = true;
            this.name.name1 = landmarks[9].landmarkName;
            this.name.description = landmarks[9].landmarkDescription;
            this.name.imagelink = landmarks[9].imageLink;
            this.name.checkin = this.calculateCount("Sea Foam")
        },

        route25() {
            console.log(routes[24]);
            this.openDrawer = true;
            this.name.name1 = routes[24].routeName;
            this.name.description = routes[24].description;
            this.name.imagelink = routes[24].routeImage;
            this.name.checkin = this.calculateCount("Route 22")
        },

        route24() {
            console.log(routes[23]);
            this.openDrawer = true;
            this.name.name1 = routes[23].routeName;
            this.name.description = routes[23].description;
            this.name.imagelink = routes[23].routeImage;
            this.name.checkin = this.calculateCount("Route 24")
        },

        route9() {
            console.log(routes[8]);
            this.openDrawer = true;
            this.name.name1 = routes[8].routeName;
            this.name.description = routes[8].description;
            this.name.imagelink = routes[8].routeImage;
            this.name.checkin = this.calculateCount("Route 9")
        },

        rockTunnel() {
            this.openDrawer = true;
            this.name.name1 = landmarks[4].landmarkName;
            this.name.description = landmarks[4].landmarkDescription;
            this.name.imagelink = landmarks[4].imageLink;
            this.name.checkin = this.calculateCount("Rock Tunnel")
        },

        route10() {
            console.log(routes[9]);
            this.openDrawer = true;
            this.name.name1 = routes[9].routeName;
            this.name.description = routes[9].description;
            this.name.imagelink = routes[9].routeImage;
            this.name.checkin = this.calculateCount("Route 10")
        },

        route11() {
            console.log(routes[10]);
            this.openDrawer = true;
            this.name.name1 = routes[10].routeName;
            this.name.description = routes[10].description;
            this.name.imagelink = routes[10].routeImage;
            this.name.checkin = this.calculateCount("Route 11")
        },

        route12() {
            console.log(routes[11]);
            this.openDrawer = true;
            this.name.name1 = routes[11].routeName;
            this.name.description = routes[11].description;
            this.name.imagelink = routes[11].routeImage;
            this.name.checkin = this.calculateCount("Route 12")
        },

        route13() {
            console.log(routes[12]);
            this.openDrawer = true;
            this.name.name1 = routes[12].routeName;
            this.name.description = routes[12].description;
            this.name.imagelink = routes[12].routeImage;
            this.name.checkin = this.calculateCount("Route 13")
        },

        route14() {
            console.log(routes[13]);
            this.openDrawer = true;
            this.name.name1 = routes[13].routeName;
            this.name.description = routes[13].description;
            this.name.imagelink = routes[13].routeImage;
            this.name.checkin = this.calculateCount("Route 14")
        },

        route15() {
            console.log(routes[14]);
            this.openDrawer = true;
            this.name.name1 = routes[14].routeName;
            this.name.description = routes[14].description;
            this.name.imagelink = routes[14].routeImage;
            this.name.checkin = this.calculateCount("Route 15")
        },

        route16() {
            console.log(routes[15]);
            this.openDrawer = true;
            this.name.name1 = routes[15].routeName;
            this.name.description = routes[15].description;
            this.name.imagelink = routes[15].routeImage;
            this.name.checkin = this.calculateCount("Route 16")
        },

        route17() {
            console.log(routes[16]);
            this.openDrawer = true;
            this.name.name1 = routes[16].routeName;
            this.name.description = routes[16].description;
            this.name.imagelink = routes[16].routeImage;
            this.name.checkin = this.calculateCount("Route 17")
        },

        route18() {
            console.log(routes[17]);
            this.openDrawer = true;
            this.name.name1 = routes[17].routeName;
            this.name.description = routes[17].description;
            this.name.imagelink = routes[17].routeImage;
            this.name.checkin = this.calculateCount("Route 18")
        },

        route19() {
            console.log(routes[18]);
            this.openDrawer = true;
            this.name.name1 = routes[18].routeName;
            this.name.description = routes[18].description;
            this.name.imagelink = routes[18].routeImage;
            this.name.checkin = this.calculateCount("Route 19")
        },

        route20() {
            console.log(routes[19]);
            this.openDrawer = true;
            this.name.name1 = routes[19].routeName;
            this.name.description = routes[19].description;
            this.name.imagelink = routes[19].routeImage;
            this.name.checkin = this.calculateCount("Route 20")
        },

        route21() {
            console.log(routes[20]);
            this.openDrawer = true;
            this.name.name1 = routes[20].routeName;
            this.name.description = routes[20].description;
            this.name.imagelink = routes[20].routeImage;
            this.name.checkin = this.calculateCount("Route 21")
        },

        route22() {
            console.log(routes[22]);
            this.openDrawer = true;
            this.name.name1 = routes[21].routeName;
            this.name.description = routes[21].description;
            this.name.imagelink = routes[21].routeImage;
            this.name.checkin = this.calculateCount("Route 22")
        },

        route23() {
            console.log(routes[23]);
            this.openDrawer = true;
            this.name.name1 = routes[22].routeName;
            this.name.description = routes[22].description;
            this.name.imagelink = routes[22].routeImage;
            this.name.checkin = this.calculateCount("Route 23")
        },

        route26() {
            console.log(routes[25]);
            this.openDrawer = true;
            this.name.name1 = routes[25].routeName;
            this.name.description = routes[25].description;
            this.name.imagelink = routes[25].routeImage;
            this.name.checkin = this.calculateCount("Route 25")
        },

        route27() {
            console.log(routes[26]);
            this.openDrawer = true;
            this.name.name1 = routes[26].routeName;
            this.name.description = routes[26].description;
            this.name.imagelink = routes[26].routeImage;
            this.name.checkin = this.calculateCount("Route 27")
        },

        route28() {
            console.log(routes[27]);
            this.openDrawer = true;
            this.name.name1 = routes[27].routeName;
            this.name.description = routes[27].description;
            this.name.imagelink = routes[27].routeImage;
            this.name.checkin = this.calculateCount("Route 28")
        },
        pallettown() {
            this.openDrawer = true;
            this.name.name1 = cities[0].cityName;
            this.name.description = cities[0].description;
            this.name.imagelink = cities[0].cityImage;
            this.name.checkin = this.calculateCount("Pallet Town")
        },
        saffron() {
            this.openDrawer = true;
            this.name.name1 = cities[1].cityName;
            this.name.description = cities[1].description;
            this.name.imagelink = cities[1].cityImage;
            this.name.checkin = this.calculateCount("Saffron City")
        },
        cinnabar() {
            this.openDrawer = true;
            this.name.name1 = cities[2].cityName;
            this.name.description = cities[2].description;
            this.name.imagelink = cities[2].cityImage;
            this.name.checkin = this.calculateCount("Cinnabar Island")
        },
        lavenderTown() {
            this.openDrawer = true;
            this.name.name1 = cities[3].cityName;
            this.name.description = cities[3].description;
            this.name.imagelink = cities[3].cityImage;
            this.name.checkin = this.calculateCount("Lavender Town")
        },
        vermillian() {
            this.openDrawer = true;
            this.name.name1 = cities[4].cityName;
            this.name.description = cities[4].description;
            this.name.imagelink = cities[4].cityImage;
            this.name.checkin = this.calculateCount("Vermilion City")
        },
        viridian() {
            this.openDrawer = true;
            this.name.name1 = cities[5].cityName;
            this.name.description = cities[5].description;
            this.name.imagelink = cities[5].cityImage;
            this.name.checkin = this.calculateCount("Viridian City")
        },
        cerleanCity() {
            console.log(cities[6]);
            this.openDrawer = true;
            this.name.name1 = cities[6].cityName;
            this.name.description = cities[6].description;
            this.name.imagelink = cities[6].cityImage;
            this.name.checkin = this.calculateCount("Cerulean City")
        },
        pewter() {
            this.openDrawer = true;
            this.name.name1 = cities[7].cityName;
            this.name.description = cities[7].description;
            this.name.imagelink = cities[7].cityImage;
            this.name.checkin = this.calculateCount("Pewter City")
        },
        celadon() {
            this.openDrawer = true;
            this.name.name1 = cities[8].cityName;
            this.name.description = cities[8].description;
            this.name.imagelink = cities[8].cityImage;
            this.name.checkin = this.calculateCount("Celedan City")
        },
        fuchia() {
            this.openDrawer = true;
            this.name.name1 = cities[9].cityName;
            this.name.description = cities[9].description;
            this.name.imagelink = cities[9].cityImage;
            this.name.checkin = this.calculateCount("Fuchsia City")
        },

        boulder() {
            console.log(badges[0]);
            this.openDrawer = true;
            this.name.name1 = badges[0].badgeName;
            this.name.description = badges[0].badgeDescription;
            this.name.imagelink = badges[0].badgeImage;
            this.name.checkin = this.calculateCount("Boulder City")
        },
        cascade() {
            console.log(badges[1]);
            this.openDrawer = true;
            this.name.name1 = badges[1].badgeName;
            this.name.description = badges[1].badgeDescription;
            this.name.imagelink = badges[1].badgeImage;
            this.name.checkin = this.calculateCount("cascade")
        },
        thunder() {
            console.log(badges[2]);
            this.openDrawer = true;
            this.name.name1 = badges[2].badgeName;
            this.name.description = badges[2].badgeDescription;
            this.name.imagelink = badges[2].badgeImage;
            this.name.checkin = this.calculateCount("Thundercity")
        },
        rainbow() {
            console.log(badges[3]);
            this.openDrawer = true;
            this.name.name1 = badges[3].badgeName;
            this.name.description = badges[3].badgeDescription;
            this.name.imagelink = badges[3].badgeImage;
            this.name.checkin = this.calculateCount("Rainbow")
        },

        soul() {
            console.log(badges[4]);
            this.openDrawer = true;
            this.name.name1 = badges[4].badgeName;
            this.name.description = badges[4].badgeDescription;
            this.name.imagelink = badges[4].badgeImage;
            this.name.checkin = this.calculateCount("Soul")
        },

        mash() {
            console.log(badges[5]);
            this.openDrawer = true;
            this.name.name1 = badges[5].badgeName;
            this.name.description = badges[5].badgeDescription;
            this.name.imagelink = badges[5].badgeImage;
            this.name.checkin = this.calculateCount("Mash")
        },
        volcano() {
            console.log(badges[6]);
            this.openDrawer = true;
            this.name.name1 = badges[6].badgeName;
            this.name.description = badges[6].badgeDescription;
            this.name.imagelink = badges[6].badgeImage;
            this.name.checkin = this.calculateCount("Volcano")
        },
        earth() {
            console.log(badges[7]);
            this.openDrawer = true;
            this.name.name1 = badges[7].badgeName;
            this.name.description = badges[7].badgeDescription;
            this.name.imagelink = badges[7].badgeImage;
            this.name.checkin = this.calculateCount("Earth")
        },

    },
};
</script>

<style scoped>
.te {
    position: relative;
    top: 0px;
    background-color: #8e91e8;
    overflow: scroll;
}

.imagestyle {
    height: 320px;
    width:100%
}

area {
    cursor: pointer;
}

.image {
    position: relative;
    top: 10px;
    left: 57px;
}

.desc {
    position: relative;
    top: 10px;
    text-align: justify;
    
}

.desc1{
    position: relative;
    top: 30px;
    text-align: justify;
}
.button {
    position: relative;
    top: 40px;
}

.footer {
    position: relative;
    top: 20px;
}

.tests {
    position: relative;
}

.link {
    position: relative;
    top: 80px;
    left: 370px;
}
</style>
